stages:
  - stage: CI
    variables:
      - name: app.root
        value: $(System.DefaultWorkingDirectory)/app
      - name: app.jdkVersion
        value: 1.11
      - name: GRADLE_USER_HOME
        value: $(Pipeline.Workspace)/.gradle
      - name: configuration.sonar.exclusions
        value: ""
      - name: configuration.sonar.coverage.exclusions
        value: ""
      - name: configuration.test.report.path
        value: $(app.root)/build/reports/jacoco/test/jacocoTestReport.xml

    jobs:
      - job: Build
        steps:
          - checkout: self

          - task: SonarCloudPrepare@1
            displayName: Sonar Prepare
            inputs:
              SonarCloud: $(SONAR_CLOUD)
              organization: $(SONAR_ORGANIZATION)
              scannerMode: Other
              projectKey: $(SONAR_PROJECT_KEY)
              projectName: $(SONAR_PROJECT_NAME)
              extraProperties: |
                sonar.cpd.exclusions=$(configuration.sonar.exclusions)
                sonar.coverage.exclusions=$(configuration.sonar.coverage.exclusions)
                sonar.jacoco.reportPaths=$(configuration.test.report.path)
                sonar.groovy.jacoco.reportPath=$(configuration.test.report.path)
                sonar.junit.reportPaths=$(configuration.test.report.path)
                
          - task: Cache@2
            displayName: Gradle Cache
            inputs:
              key: gradle | $(app.root)/gradle/wrapper/gradle-wrapper.properties
              restoreKeys: |
                gradle | $(app.root)/gradle/wrapper/gradle-wrapper.properties
                gradle
              path: $(GRADLE_USER_HOME)

          - task: Gradle@2.176.0
            displayName: Gradle Classes build
            inputs:
              tasks: classes --build-cache
              workingDirectory: $(app.root)
              jdkVersionOption: $(app.jdkVersion)
              gradleWrapperFile: $(app.root)/gradlew
              publishJUnitResults: false
              sonarQubeRunAnalysis: true

          - task: Gradle@2.176.0
            displayName: Gradle Tests run
            inputs:
              tasks: -Duser.country=$(configuration.test.country) -Duser.language=$(configuration.test.language) -Duser.timezone=$(configuration.test.timezone) test
              workingDirectory: $(app.root)
              jdkVersionOption: $(app.jdkVersion)
              gradleWrapperFile: $(app.root)/gradlew
              testRunTitle: Unit
              publishJUnitResults: true

          - task: PublishCodeCoverageResults@1.175.1
            displayName: Publish Code Coverage
            inputs:
              codeCoverageTool: jaCoCo
              pathToSources: $(app.root)/src/main/kotlin
              summaryFileLocation: $(configuration.test.report.path)
              failIfCoverageEmpty: true

          - task: Gradle@2.176.0
            displayName: Gradle Assemble classes
            inputs:
              tasks: assemble
              workingDirectory: $(app.root)
              jdkVersionOption: $(app.jdkVersion)
              gradleWrapperFile: $(app.root)/gradlew
              publishJUnitResults: false

          - task: Gradle@2.176.0
            displayName: Gradle Stop Daemon
            inputs:
              tasks: --stop
              workingDirectory: $(app.root)
              jdkVersionOption: $(app.jdkVersion)
              gradleWrapperFile: $(app.root)/gradlew
              publishJUnitResults: false

          - task: SonarCloudPublish@1
            displayName: Sonar Publish
            inputs:
              pollingTimeoutSec: '300'

          - task: sonarcloud-buildbreaker@2
            displayName: "Sonar Build Breaker"
            inputs:
              SonarCloud: "$(configuration.sonar.serviceconnection)"
              organization: "$(configuration.sonar.organization)"
